version: '3.8'

services:
  admin:
    build:
      context: ./smartparking
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:smartparking"
    environment:
      - ENVIRONMENT=dev
    ports:
      - "${ADMIN_PORT}:8000"
    volumes:
      - "./smartparking:/home/smartparking/smartparking"
      - "./staticfiles:/home/smartparking/staticfiles"
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --no-post-process &&
        chown -R www-data:www-data /home/smartparking/staticfiles &&
        python create_superuser_and_site.py &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:api"
    ports:
      - "${API_PORT}:8001"
    environment:
      - ENVIRONMENT=dev
    volumes:
      - "./api:/home/smartparking/api"
    depends_on:
      - db
    command: >
      sh -c "uvicorn smartparking.main:app --host 0.0.0.0 --port 8001"
    restart: always

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    volumes:
      - "minio_data:/data"
    command: server --console-address ":9001" /data

volumes:
  minio_data:



