version: '3.8'

services:
  admin:
    build:
      context: ./smartparking
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:smartparking"
    environment:
      - ENVIRONMENT=stg
    ports:
      - "${ADMIN_PORT}:8000"
    volumes:
      - "./smartparking:/home/smartparking/smartparking"
      - "./staticfiles:/home/smartparking/staticfiles"
    depends_on:
      - db_stg
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --no-post-process &&
        chown -R www-data:www-data /home/smartparking/staticfiles &&
        python create_superuser_and_site.py &&
        gunicorn smartparking.wsgi:application --workers 3 --bind 0.0.0.0:8000"
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:api"
    ports:
      - "${API_PORT}:8001"
    environment:
      - ENVIRONMENT=stg
    volumes:
      - "./api:/home/smartparking/api"
    depends_on:
      - db_stg
    command: >
      sh -c "uvicorn smartparking.main:app --host 0.0.0.0 --port 8001"
    restart: always
